import { mutation } from "./_generated/server";

// ~91 Questions for Found - organized by 6 categories
// Each question has a stable questionKey for reliable referencing
// Restructured with Hinge-style filters front-loaded and checklist type for partner preferences

export const QUESTIONS = [
  // ============================================
  // CATEGORY 1: The Basics (Questions 1-33)
  // Hinge-style filters + demographic compatibility + substances
  // ============================================
  
  // Relationship Goals
  {
    order: 1,
    questionKey: "relationship_goals_self",
    text: "What are you looking for?",
    type: "multiple_choice" as const,
    category: "The Basics",
    options: [
      "Life partner",
      "Long-term relationship",
      "Figuring it out",
      "Something casual",
    ],
  },
  {
    order: 2,
    questionKey: "relationship_goals_pref",
    text: "What are you open to in a partner?",
    type: "checklist" as const,
    category: "The Basics",
    linkedQuestionKey: "relationship_goals_self",
    options: [
      "Open to any",
      "Life partner",
      "Long-term relationship",
      "Figuring it out",
      "Something casual",
    ],
  },
  
  // Relationship Style
  {
    order: 3,
    questionKey: "relationship_style_self",
    text: "What's your relationship style?",
    type: "multiple_choice" as const,
    category: "The Basics",
    options: [
      "Monogamy",
      "Open to non-monogamy",
      "Non-monogamous",
      "Figuring it out",
    ],
  },
  {
    order: 4,
    questionKey: "relationship_style_pref",
    text: "What are you open to in a partner?",
    type: "checklist" as const,
    category: "The Basics",
    linkedQuestionKey: "relationship_style_self",
    options: [
      "Open to any",
      "Monogamy",
      "Open to non-monogamy",
      "Non-monogamous",
      "Figuring it out",
    ],
  },
  
  // Children - Has
  {
    order: 5,
    questionKey: "has_children_self",
    text: "Do you have children?",
    type: "multiple_choice" as const,
    category: "The Basics",
    options: ["Yes", "No"],
  },
  {
    order: 6,
    questionKey: "has_children_pref",
    text: "Are you open to partners with children?",
    type: "checklist" as const,
    category: "The Basics",
    linkedQuestionKey: "has_children_self",
    options: ["Open to any", "Yes", "No"],
  },
  
  // Children - Wants
  {
    order: 7,
    questionKey: "wants_children_self",
    text: "Do you want children?",
    type: "multiple_choice" as const,
    category: "The Basics",
    options: [
      "Want children",
      "Don't want children",
      "Open to children",
      "Have children, want more",
      "Have children, don't want more",
    ],
  },
  {
    order: 8,
    questionKey: "wants_children_pref",
    text: "What are you open to in a partner?",
    type: "checklist" as const,
    category: "The Basics",
    linkedQuestionKey: "wants_children_self",
    options: [
      "Open to any",
      "Want children",
      "Don't want children",
      "Open to children",
      "Have children, want more",
      "Have children, don't want more",
    ],
  },
  {
    order: 9,
    questionKey: "kids_timeline",
    text: "What's your ideal timeline for kids?",
    type: "multiple_choice" as const,
    category: "The Basics",
    hasDealbreaker: true,
    options: [
      "ASAP",
      "1-2 years",
      "3-5 years",
      "5+ years",
      "Not sure",
      "N/A",
    ],
  },
  
  // Height
  {
    order: 10,
    questionKey: "height_self",
    text: "How tall are you?",
    type: "scale" as const,
    category: "The Basics",
    scaleMin: 48, // 4'0"
    scaleMax: 84, // 7'0"
    scaleMinLabel: "4'0\"",
    scaleMaxLabel: "7'0\"",
  },
  {
    order: 11,
    questionKey: "height_pref",
    text: "What is your ideal height range for a partner?",
    type: "range" as const,
    category: "The Basics",
    scaleMin: 48, // 4'0"
    scaleMax: 84, // 7'0"
    scaleMinLabel: "4'0\"",
    scaleMaxLabel: "7'0\"",
    hasDealbreaker: true,
  },
  
  // Location & Age
  {
    order: 12,
    questionKey: "hometown",
    text: "Where did you grow up?",
    type: "text" as const,
    category: "The Basics",
  },
  {
    order: 13,
    questionKey: "age_range_pref",
    text: "What is your ideal age range for a partner?",
    type: "range" as const,
    category: "The Basics",
    scaleMin: 18,
    scaleMax: 80,
    scaleMinLabel: "18",
    scaleMaxLabel: "80",
    hasDealbreaker: true,
  },
  {
    order: 14,
    questionKey: "distance_pref",
    text: "How far are you willing to travel for a match?",
    type: "multiple_choice" as const,
    category: "The Basics",
    hasDealbreaker: true,
    options: [
      "5 miles",
      "15 miles",
      "30 miles",
      "50 miles",
      "100+ miles",
      "Willing to relocate",
    ],
  },
  
  // Ethnicity
  {
    order: 15,
    questionKey: "ethnicity_self",
    text: "What's your ethnicity?",
    type: "checklist" as const,
    category: "The Basics",
    options: [
      "Asian",
      "Black / African Descent",
      "Hispanic / Latino",
      "Middle Eastern",
      "Native American / Indigenous",
      "Pacific Islander",
      "South Asian",
      "White / Caucasian",
      "Other",
      "Prefer not to say",
    ],
  },
  {
    order: 16,
    questionKey: "ethnicity_pref",
    text: "What ethnicities are you open to in a partner?",
    type: "checklist" as const,
    category: "The Basics",
    linkedQuestionKey: "ethnicity_self",
    options: [
      "Open to any",
      "Asian",
      "Black / African Descent",
      "Hispanic / Latino",
      "Middle Eastern",
      "Native American / Indigenous",
      "Pacific Islander",
      "South Asian",
      "White / Caucasian",
      "Other",
    ],
  },
  
  // Religion
  {
    order: 17,
    questionKey: "religion_self",
    text: "What religion do you practice?",
    type: "multiple_choice" as const,
    category: "The Basics",
    options: [
      "Christian",
      "Catholic",
      "Jewish",
      "Muslim",
      "Hindu",
      "Buddhist",
      "Spiritual",
      "Agnostic",
      "Atheist",
      "Other",
      "None",
    ],
  },
  {
    order: 18,
    questionKey: "religion_pref",
    text: "What religions are you open to?",
    type: "checklist" as const,
    category: "The Basics",
    linkedQuestionKey: "religion_self",
    options: [
      "Open to any",
      "Christian",
      "Catholic",
      "Jewish",
      "Muslim",
      "Hindu",
      "Buddhist",
      "Spiritual",
      "Agnostic",
      "Atheist",
      "Other",
      "None",
    ],
  },
  {
    order: 19,
    questionKey: "religion_importance",
    text: "How important is religion in your life?",
    type: "scale" as const,
    category: "The Basics",
    scaleMin: 1,
    scaleMax: 10,
    scaleMinLabel: "Not at all",
    scaleMaxLabel: "Central to my life",
  },
  
  // Politics
  {
    order: 20,
    questionKey: "politics_self",
    text: "What's your political leaning?",
    type: "multiple_choice" as const,
    category: "The Basics",
    options: [
      "Very liberal",
      "Liberal",
      "Moderate",
      "Conservative",
      "Very conservative",
      "Libertarian",
      "Apolitical",
    ],
  },
  {
    order: 21,
    questionKey: "politics_pref",
    text: "What political views are you open to?",
    type: "checklist" as const,
    category: "The Basics",
    linkedQuestionKey: "politics_self",
    options: [
      "Open to any",
      "Very liberal",
      "Liberal",
      "Moderate",
      "Conservative",
      "Very conservative",
      "Libertarian",
      "Apolitical",
    ],
  },
  {
    order: 22,
    questionKey: "politics_importance",
    text: "How important is politics in your life?",
    type: "scale" as const,
    category: "The Basics",
    scaleMin: 1,
    scaleMax: 10,
    scaleMinLabel: "Not at all",
    scaleMaxLabel: "It's my life",
  },
  
  // Education
  {
    order: 23,
    questionKey: "education_self",
    text: "What's your highest education level?",
    type: "multiple_choice" as const,
    category: "The Basics",
    options: [
      "High school",
      "Some college",
      "Bachelor's degree",
      "Master's degree",
      "Doctorate",
      "Trade school",
    ],
  },
  {
    order: 24,
    questionKey: "education_pref",
    text: "What education levels are you open to?",
    type: "checklist" as const,
    category: "The Basics",
    linkedQuestionKey: "education_self",
    options: [
      "Open to any",
      "High school",
      "Some college",
      "Bachelor's degree",
      "Master's degree",
      "Doctorate",
      "Trade school",
    ],
  },
  {
    order: 25,
    questionKey: "basics_extra",
    text: "Anything else we should know to find your match?",
    type: "essay" as const,
    category: "The Basics",
  },
  
  // Substances
  {
    order: 26,
    questionKey: "alcohol_self",
    text: "How often do you drink alcohol?",
    type: "multiple_choice" as const,
    category: "The Basics",
    options: ["Never", "Rarely", "Socially", "Regularly", "Daily"],
  },
  {
    order: 27,
    questionKey: "alcohol_pref",
    text: "What are you open to in a partner?",
    type: "checklist" as const,
    category: "The Basics",
    linkedQuestionKey: "alcohol_self",
    options: ["Open to any", "Never", "Rarely", "Socially", "Regularly", "Daily"],
  },
  {
    order: 28,
    questionKey: "smoking_self",
    text: "Do you smoke cigarettes or vape?",
    type: "multiple_choice" as const,
    category: "The Basics",
    options: ["Never", "Socially", "Regularly", "Daily"],
  },
  {
    order: 29,
    questionKey: "smoking_pref",
    text: "What are you open to in a partner?",
    type: "checklist" as const,
    category: "The Basics",
    linkedQuestionKey: "smoking_self",
    options: ["Open to any", "Never", "Socially", "Regularly", "Daily"],
  },
  {
    order: 30,
    questionKey: "marijuana_self",
    text: "Do you use marijuana?",
    type: "multiple_choice" as const,
    category: "The Basics",
    options: ["Never", "Rarely", "Sometimes", "Regularly"],
  },
  {
    order: 31,
    questionKey: "marijuana_pref",
    text: "What are you open to in a partner?",
    type: "checklist" as const,
    category: "The Basics",
    linkedQuestionKey: "marijuana_self",
    options: ["Open to any", "Never", "Rarely", "Sometimes", "Regularly"],
  },
  {
    order: 32,
    questionKey: "drugs_self",
    text: "Do you use other recreational drugs?",
    type: "multiple_choice" as const,
    category: "The Basics",
    options: ["Never", "Very rarely", "Occasionally", "Regularly"],
  },
  {
    order: 33,
    questionKey: "drugs_pref",
    text: "What are you open to in a partner?",
    type: "checklist" as const,
    category: "The Basics",
    linkedQuestionKey: "drugs_self",
    options: ["Open to any", "Never", "Very rarely", "Occasionally", "Regularly"],
  },

  // ============================================
  // CATEGORY 2: Who You Are (Questions 34-46)
  // Personality, values, openness
  // ============================================
  {
    order: 34,
    questionKey: "social_description",
    text: "How would you describe yourself socially?",
    type: "multiple_choice" as const,
    category: "Who You Are",
    options: [
      "Very introverted",
      "Introverted",
      "Ambivert",
      "Extroverted",
      "Very extroverted",
    ],
  },
  {
    order: 35,
    questionKey: "openness_new_experiences",
    text: "How open are you to new experiences?",
    type: "scale" as const,
    category: "Who You Are",
    scaleMin: 1,
    scaleMax: 10,
    scaleMinLabel: "Creature of habit",
    scaleMaxLabel: "Always seeking novelty",
  },
  {
    order: 36,
    questionKey: "handle_change",
    text: "How do you handle change?",
    type: "multiple_choice" as const,
    category: "Who You Are",
    options: [
      "Love it",
      "Adapt well",
      "Need time to adjust",
      "Prefer stability",
    ],
  },
  {
    order: 37,
    questionKey: "ambition_level",
    text: "How would you describe your ambition?",
    type: "scale" as const,
    category: "Who You Are",
    scaleMin: 1,
    scaleMax: 10,
    scaleMinLabel: "Content with simple life",
    scaleMaxLabel: "Highly driven",
  },
  {
    order: 38,
    questionKey: "emotional_expressiveness",
    text: "How emotionally expressive are you?",
    type: "scale" as const,
    category: "Who You Are",
    scaleMin: 1,
    scaleMax: 10,
    scaleMinLabel: "Very private",
    scaleMaxLabel: "Open book",
  },
  {
    order: 39,
    questionKey: "personal_growth_importance",
    text: "How important is personal growth to you?",
    type: "scale" as const,
    category: "Who You Are",
    scaleMin: 1,
    scaleMax: 10,
    scaleMinLabel: "Not a focus",
    scaleMaxLabel: "Top priority",
  },
  {
    order: 40,
    questionKey: "communication_style",
    text: "How would you describe your communication style?",
    type: "multiple_choice" as const,
    category: "Who You Are",
    options: [
      "Direct and blunt",
      "Diplomatic",
      "Passive",
      "Depends on context",
    ],
  },
  {
    order: 41,
    questionKey: "competitiveness",
    text: "How competitive are you?",
    type: "scale" as const,
    category: "Who You Are",
    scaleMin: 1,
    scaleMax: 10,
    scaleMinLabel: "Not competitive",
    scaleMaxLabel: "Very competitive",
  },
  {
    order: 42,
    questionKey: "spontaneity",
    text: "How spontaneous vs. planned are you?",
    type: "scale" as const,
    category: "Who You Are",
    scaleMin: 1,
    scaleMax: 10,
    scaleMinLabel: "Very spontaneous",
    scaleMaxLabel: "Very structured",
  },
  {
    order: 43,
    questionKey: "alone_time_need",
    text: "How important is alone time to you?",
    type: "scale" as const,
    category: "Who You Are",
    scaleMin: 1,
    scaleMax: 10,
    scaleMinLabel: "Rarely need it",
    scaleMaxLabel: "Essential daily",
  },
  {
    order: 44,
    questionKey: "life_priority",
    text: "What's most important to you in life right now?",
    type: "multiple_choice" as const,
    category: "Who You Are",
    options: [
      "Career",
      "Relationships",
      "Family",
      "Personal growth",
      "Health",
      "Having fun",
      "Balance",
    ],
  },
  {
    order: 45,
    questionKey: "core_values",
    text: "What are your core values?",
    type: "essay" as const,
    category: "Who You Are",
  },
  {
    order: 46,
    questionKey: "never_compromise",
    text: "What's something you'd never compromise on?",
    type: "essay" as const,
    category: "Who You Are",
  },

  // ============================================
  // CATEGORY 3: Relationship Style (Questions 47-60)
  // Communication, attachment, expectations
  // ============================================
  {
    order: 47,
    questionKey: "conflict_handling",
    text: "How do you prefer to handle conflict?",
    type: "multiple_choice" as const,
    category: "Relationship Style",
    options: [
      "Address it immediately",
      "Cool off first, then discuss",
      "Write out my thoughts",
      "Let small things go",
      "Avoid conflict when possible",
    ],
  },
  {
    order: 48,
    questionKey: "attachment_style",
    text: "What's your attachment style?",
    type: "multiple_choice" as const,
    category: "Relationship Style",
    options: [
      "Secure",
      "Anxious",
      "Avoidant",
      "Disorganized",
      "Not sure",
    ],
  },
  {
    order: 49,
    questionKey: "together_time_need",
    text: "How much together time do you need in a relationship?",
    type: "scale" as const,
    category: "Relationship Style",
    scaleMin: 1,
    scaleMax: 10,
    scaleMinLabel: "Lots of independence",
    scaleMaxLabel: "Constant togetherness",
  },
  {
    order: 50,
    questionKey: "love_language",
    text: "What's your love language?",
    type: "multiple_choice" as const,
    category: "Relationship Style",
    options: [
      "Words of affirmation",
      "Quality time",
      "Physical touch",
      "Acts of service",
      "Receiving gifts",
    ],
  },
  {
    order: 51,
    questionKey: "texting_style",
    text: "What's your texting style in a relationship?",
    type: "multiple_choice" as const,
    category: "Relationship Style",
    options: [
      "Constant communication",
      "Regular check-ins",
      "A few messages a day",
      "Minimal texting",
      "Prefer calls",
    ],
  },
  {
    order: 52,
    questionKey: "discuss_emotions",
    text: "How comfortable are you discussing difficult emotions?",
    type: "scale" as const,
    category: "Relationship Style",
    scaleMin: 1,
    scaleMax: 10,
    scaleMinLabel: "Very uncomfortable",
    scaleMaxLabel: "Very comfortable",
  },
  {
    order: 53,
    questionKey: "jealousy_level",
    text: "How jealous do you tend to be?",
    type: "scale" as const,
    category: "Relationship Style",
    scaleMin: 1,
    scaleMax: 10,
    scaleMinLabel: "Not at all",
    scaleMaxLabel: "Very jealous",
  },
  {
    order: 54,
    questionKey: "physical_intimacy_importance",
    text: "How important is physical intimacy to you?",
    type: "scale" as const,
    category: "Relationship Style",
    scaleMin: 1,
    scaleMax: 10,
    scaleMinLabel: "Not important",
    scaleMaxLabel: "Very important",
  },
  {
    order: 55,
    questionKey: "physical_attraction_importance",
    text: "How important is physical attraction to you?",
    type: "scale" as const,
    category: "Relationship Style",
    scaleMin: 1,
    scaleMax: 10,
    scaleMinLabel: "Not important",
    scaleMaxLabel: "Very important",
  },
  {
    order: 56,
    questionKey: "pda_comfort",
    text: "How do you feel about PDA?",
    type: "multiple_choice" as const,
    category: "Relationship Style",
    options: [
      "Love it",
      "Fine with it",
      "Okay in moderation",
      "Prefer to keep it private",
    ],
  },
  {
    order: 57,
    questionKey: "finances_handling",
    text: "How do you handle finances in a relationship?",
    type: "multiple_choice" as const,
    category: "Relationship Style",
    hasDealbreaker: true,
    options: [
      "Fully shared",
      "Mostly shared",
      "Split 50/50",
      "Mostly separate",
      "Depends on the situation",
    ],
  },
  {
    order: 58,
    questionKey: "financial_status_importance",
    text: "How important is similar income/financial status?",
    type: "scale" as const,
    category: "Relationship Style",
    scaleMin: 1,
    scaleMax: 10,
    scaleMinLabel: "Not important",
    scaleMaxLabel: "Very important",
  },
  {
    order: 59,
    questionKey: "healthy_relationship",
    text: "What does a healthy relationship look like to you?",
    type: "essay" as const,
    category: "Relationship Style",
  },
  {
    order: 60,
    questionKey: "relationship_dealbreaker",
    text: "What's your biggest relationship dealbreaker?",
    type: "essay" as const,
    category: "Relationship Style",
  },

  // ============================================
  // CATEGORY 4: Lifestyle (Questions 61-72)
  // Daily life, health, social patterns
  // ============================================
  {
    order: 61,
    questionKey: "morning_night",
    text: "Are you a morning person or night owl?",
    type: "multiple_choice" as const,
    category: "Lifestyle",
    options: [
      "Early bird",
      "Morning-leaning",
      "Flexible",
      "Night-leaning",
      "Night owl",
    ],
  },
  {
    order: 62,
    questionKey: "exercise_frequency",
    text: "How often do you exercise?",
    type: "multiple_choice" as const,
    category: "Lifestyle",
    options: [
      "Never",
      "Monthly",
      "Weekly",
      "Several times a week",
      "Daily",
    ],
  },
  {
    order: 63,
    questionKey: "diet_strictness",
    text: "How strict is your diet?",
    type: "scale" as const,
    category: "Lifestyle",
    scaleMin: 1,
    scaleMax: 10,
    scaleMinLabel: "Eat anything",
    scaleMaxLabel: "Very strict",
  },
  {
    order: 64,
    questionKey: "physical_health",
    text: "How would you rate your physical health?",
    type: "scale" as const,
    category: "Lifestyle",
    scaleMin: 1,
    scaleMax: 10,
    scaleMinLabel: "Poor",
    scaleMaxLabel: "Excellent",
  },
  {
    order: 65,
    questionKey: "mental_health",
    text: "How would you rate your mental health?",
    type: "scale" as const,
    category: "Lifestyle",
    scaleMin: 1,
    scaleMax: 10,
    scaleMinLabel: "Struggling",
    scaleMaxLabel: "Thriving",
  },
  {
    order: 66,
    questionKey: "pets_have",
    text: "Do you have pets?",
    type: "multiple_choice" as const,
    category: "Lifestyle",
    options: [
      "Yes, dogs",
      "Yes, cats",
      "Yes, other",
      "No, but want them",
      "No, don't want them",
    ],
  },
  {
    order: 67,
    questionKey: "pets_feel",
    text: "How do you feel about pets?",
    type: "multiple_choice" as const,
    category: "Lifestyle",
    options: [
      "Love them",
      "Like them",
      "Neutral",
      "Allergic",
      "Prefer none",
    ],
  },
  {
    order: 68,
    questionKey: "out_vs_in",
    text: "How often do you go out vs. stay in?",
    type: "scale" as const,
    category: "Lifestyle",
    scaleMin: 1,
    scaleMax: 10,
    scaleMinLabel: "Homebody",
    scaleMaxLabel: "Always out",
  },
  {
    order: 69,
    questionKey: "social_life_description",
    text: "How would you describe your social life?",
    type: "multiple_choice" as const,
    category: "Lifestyle",
    options: [
      "Very active",
      "Moderately active",
      "Balanced",
      "Quiet",
      "Mostly solo",
    ],
  },
  {
    order: 70,
    questionKey: "friends_compatibility_importance",
    text: "How important is it that your partner gets along with your friends?",
    type: "scale" as const,
    category: "Lifestyle",
    scaleMin: 1,
    scaleMax: 10,
    scaleMinLabel: "Not important",
    scaleMaxLabel: "Essential",
  },
  {
    order: 71,
    questionKey: "weekend_activity",
    text: "How do you typically spend weekends?",
    type: "essay" as const,
    category: "Lifestyle",
  },
  {
    order: 72,
    questionKey: "health_lifestyle_notes",
    text: "Is there anything about your health or lifestyle a partner should know?",
    type: "essay" as const,
    category: "Lifestyle",
  },

  // ============================================
  // CATEGORY 5: Life & Future (Questions 73-82)
  // Goals, family, where you're headed
  // ============================================
  {
    order: 73,
    questionKey: "family_closeness",
    text: "How close are you with your family?",
    type: "scale" as const,
    category: "Life & Future",
    scaleMin: 1,
    scaleMax: 10,
    scaleMinLabel: "Not close",
    scaleMaxLabel: "Very close",
  },
  {
    order: 74,
    questionKey: "family_contact_frequency",
    text: "How often do you see or talk to family?",
    type: "multiple_choice" as const,
    category: "Life & Future",
    options: [
      "Daily",
      "Weekly",
      "Monthly",
      "A few times a year",
      "Rarely",
    ],
  },
  {
    order: 75,
    questionKey: "family_compatibility_importance",
    text: "How important is it that your partner gets along with your family?",
    type: "scale" as const,
    category: "Life & Future",
    scaleMin: 1,
    scaleMax: 10,
    scaleMinLabel: "Not important",
    scaleMaxLabel: "Essential",
  },
  {
    order: 76,
    questionKey: "settle_location",
    text: "Where do you see yourself settling down?",
    type: "multiple_choice" as const,
    category: "Life & Future",
    options: [
      "Big city",
      "Small city",
      "Suburb",
      "Small town",
      "Rural area",
      "Flexible",
    ],
  },
  {
    order: 77,
    questionKey: "location_flexibility",
    text: "How flexible are you about where you live?",
    type: "scale" as const,
    category: "Life & Future",
    hasDealbreaker: true,
    scaleMin: 1,
    scaleMax: 10,
    scaleMinLabel: "Not flexible",
    scaleMaxLabel: "Very flexible",
  },
  {
    order: 78,
    questionKey: "career_ambitions",
    text: "What are your career ambitions?",
    type: "multiple_choice" as const,
    category: "Life & Future",
    options: [
      "Highly ambitious",
      "Moderately driven",
      "Content where I am",
      "Prioritizing other things",
    ],
  },
  {
    order: 79,
    questionKey: "work_life_balance",
    text: "What's your ideal work-life balance?",
    type: "scale" as const,
    category: "Life & Future",
    scaleMin: 1,
    scaleMax: 10,
    scaleMinLabel: "Work-focused",
    scaleMaxLabel: "Life-focused",
  },
  {
    order: 80,
    questionKey: "parents_relationship",
    text: "Describe your relationship with your parents.",
    type: "essay" as const,
    category: "Life & Future",
  },
  {
    order: 81,
    questionKey: "parenting_style",
    text: "What kind of parent do you want to be?",
    type: "essay" as const,
    category: "Life & Future",
  },
  {
    order: 82,
    questionKey: "hopes_dreams",
    text: "What are your hopes and dreams?",
    type: "essay" as const,
    category: "Life & Future",
  },

  // ============================================
  // CATEGORY 6: The Deeper Stuff (Questions 83-91)
  // Philosophy, stories, what makes you you
  // ============================================
  {
    order: 83,
    questionKey: "soulmates_belief",
    text: "Do you believe in soulmates?",
    type: "multiple_choice" as const,
    category: "The Deeper Stuff",
    options: [
      "Yes, absolutely",
      "I think there are many compatible people",
      "Skeptical but open",
      "No, I don't",
    ],
  },
  {
    order: 84,
    questionKey: "love_meaning",
    text: "What does love mean to you?",
    type: "essay" as const,
    category: "The Deeper Stuff",
  },
  {
    order: 85,
    questionKey: "biggest_risk",
    text: "What's the biggest risk you've ever taken?",
    type: "essay" as const,
    category: "The Deeper Stuff",
  },
  {
    order: 86,
    questionKey: "what_shaped_you",
    text: "What shaped who you are today?",
    type: "essay" as const,
    category: "The Deeper Stuff",
  },
  {
    order: 87,
    questionKey: "main_hobbies",
    text: "What are your main hobbies?",
    type: "text" as const,
    category: "The Deeper Stuff",
  },
  {
    order: 88,
    questionKey: "partner_quirk",
    text: "What's a quirk a partner should know about?",
    type: "text" as const,
    category: "The Deeper Stuff",
  },
  {
    order: 89,
    questionKey: "why_on_app",
    text: "Why are you on this app?",
    type: "essay" as const,
    category: "The Deeper Stuff",
  },
  {
    order: 90,
    questionKey: "anything_else",
    text: "Anything else a match should know about you?",
    type: "essay" as const,
    category: "The Deeper Stuff",
  },
  {
    order: 91,
    questionKey: "interests",
    text: "What are your interests?",
    type: "interest_picker" as const,
    category: "The Deeper Stuff",
  },
];

// Category order for UI display
export const CATEGORIES = [
  "The Basics",
  "Who You Are",
  "Relationship Style",
  "Lifestyle",
  "Life & Future",
  "The Deeper Stuff",
] as const;

// Seed mutation - call this to populate the questions table
export const seedQuestions = mutation({
  args: {},
  handler: async (ctx) => {
    // Clear existing questions
    const existing = await ctx.db.query("questions").collect();
    for (const q of existing) {
      await ctx.db.delete(q._id);
    }

    // Insert all questions
    for (const question of QUESTIONS) {
      await ctx.db.insert("questions", question);
    }

    return { seeded: QUESTIONS.length };
  },
});
